name: Main workflow

on: [push, pull_request]

jobs:
  build:
    name: Build on erlang OTP ${{ matrix.otp }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ["20.3", "21.3", "22.0"]
    container:
      image: erlang:${{ matrix.otp }}
    steps:
    - uses: actions/checkout@master
    - name: compile
      run: make testgen
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    container:
      image: erlang:22.0
    steps:
    - uses: actions/checkout@master
    - name: Typecheck with dialyzer
      run: make typecheck
